[project]
name = "gittest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muzmmil Khan", email = "muzmmil.dba@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.128.8",
]

[project.scripts]
gittest = "gittest:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
